### ISSUE TITLE
网页登录按钮点击可以跳转到即刻的页面/增加可点击的跳转链接

### ISSUE THREAD

**Issue by iceytea** [coder-ysj/jike-meow#2]
作者你好，即刻喵的登录功能很是方便。
不过感觉现在有两种情况会有问题，感觉要是能调整的话，就更方便了。

1. 当处于**google浏览器的默认首页**（网址栏为空的界面），点击登录按钮，没有反应
2. 当不在即刻网页版的页面时，点击登录按钮，会提示：请在即刻网页版页面点击按钮

这两种情况，都需要我手动输入网址进入页面再点击，增加了用户的操作步骤。

因此，希望可以增加可点击的跳转链接/直接跳转页面的功能，这样可以减少一步操作，使用会更快捷。

_说实话，这个改动其实是可有可无的，因为**现在弹出的框里面网址可以直接复制**，_

但是第一种无反应的情况，希望您能查看下~

感谢！

**Comment by coder-ysj** [comment]
感谢反馈，正在着手优化。

**Comment by coder-ysj** [comment]
优化完毕，现在的逻辑是，打开插件的时候如果浏览器 tab URL 是即刻官网就显示「网页登录」，无论是否有登录，点击都会登录；如果不是即刻官网，就显示「打开官网」引导。这一特性将会在下一版本更新中加入。
