### ISSUE TITLE
反馈BUG：不支持的消息类型 点击此处反馈给作者

### ISSUE THREAD

**Issue by Tiiiis** [coder-ysj/jike-meow#4]
Hi coder-ysj,

FYI，and您了参考标题和见附件吧...

chrome 版本 69.0.3497.100（正式版本） （64 位）

: )
👍 

另外，NB。

![_20180930180028](https://user-images.githubusercontent.com/39986347/46256254-cb729980-c4da-11e8-8b98-37f6f980711c.png)

**Comment by coder-ysj** [comment]
感谢反馈，该问题已修复。

**Comment by Tiiiis** [comment]
卧槽，可以啊小伙，这么快...


| |
Tiiiis
|
|
邮箱：tiiiis@126.com
. .. ...
|
签名由网易邮箱大师定制
在2018年9月30日 18:34，Jay Yan<notifications@github.com> 写道：

感谢反馈，该问题已修复。

**Comment by Tiiiis** [comment]
重启了chrome，还是不中啊，您了抽空再看看，辛苦了。




| |
Tiiiis
|
|
邮箱：tiiiis@126.com
. .. ...
|
签名由网易邮箱大师定制
在2018年9月30日 18:36，Jay Yan<notifications@github.com> 写道：

Closed #4.

**Comment by coder-ysj** [comment]
源代码中已修复，商店版将于近日发布更新。

**Comment by Tiiiis** [comment]
好嘞，神速。


| |
Tiiiis
|
|
邮箱：tiiiis@126.com
. .. ...
|
签名由网易邮箱大师定制
在2018年9月30日 18:38，Jay Yan<notifications@github.com> 写道：

源代码中已修复，商店版将于近日发布更新。
