### ISSUE TITLE
当前正在使用的版本号: 1.2.2

### ISSUE THREAD

**Issue by Hsuanr** [coder-ysj/jike-meow#5]
<img width="400" alt="2018-10-20 10 36 37" src="https://user-images.githubusercontent.com/23187349/47256856-de183700-d4b8-11e8-95f5-565628a36660.png">
并不知道是啥

**Comment by Hsuanr** [comment]
啊 看了一下
是别人转发并评论了我的提问

**Comment by coder-ysj** [comment]
Hi, Hsuan

感谢你的反馈。
如果确实发生了这种问题，先表示抱歉了。
目前正在排查处理中，并在下一个版本中解决。

盐酥鸡
2018/10/21

Hsuan <notifications@github.com> 于2018年10月20日周六 下午11:35写道：
